# Generated by Django 5.1.2 on 2024-10-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=1000)),
                ('product_image', models.URLField(default='https://cdn.shopify.com/s/files/1/0533/2089/files/placeholder-images-image_large.png?v=1530129081')),
                ('product_rating', models.FloatField()),
                ('product_rating_count', models.PositiveIntegerField()),
                ('product_review_count', models.PositiveIntegerField()),
                ('selling_price', models.PositiveIntegerField()),
                ('mrp', models.PositiveIntegerField()),
                ('product_highlights', models.TextField()),
            ],
        ),
    ]
