# Generated by Django 5.1.2 on 2024-10-27 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
