# Generated by Django 5.1.2 on 2024-10-29 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecom', '0003_book_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='product_description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='product_details',
        ),
    ]
