# Generated by Django 5.1.2 on 2024-10-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecom', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='book',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
