# Generated by Django 5.1.2 on 2024-11-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecom', '0007_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(default='email@email.com', max_length=1000),
        ),
    ]
